# Generated by Django 5.1.2 on 2024-12-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProuct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('modelname', models.CharField(max_length=200)),
                ('device_series', models.CharField(max_length=200)),
                ('device_number', models.IntegerField()),
                ('processor_brand', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=200)),
                ('processor_model', models.CharField(max_length=50)),
                ('cpu_cache', models.CharField(max_length=50)),
                ('display_size', models.IntegerField()),
                ('display_type', models.CharField(max_length=100)),
                ('display_resolution', models.CharField(max_length=100)),
                ('touch_screen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('ram', models.CharField(max_length=100)),
                ('ram_type', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=100)),
                ('ssd', models.CharField(max_length=100)),
                ('optical_drive', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('keyboard_back_lit', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('finger_print_sensor', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('wifi', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('warranty', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brand',
            },
        ),
    ]
