# Generated by Django 5.1.2 on 2024-12-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inentory_app', '0002_alter_deviceprouct_display_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff', models.CharField(max_length=100)),
                ('lastdate', models.DateField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inentory_app.deviceprouct')),
            ],
        ),
    ]
